CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email, username)
);

CREATE TABLE IF NOT EXISTS employees
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    admission_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    salary         DECIMAL                                 NOT NULL,
    active         BOOLEAN                                 NOT NULL DEFAULT true,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_employees_user_id ON employees (user_id);
CREATE INDEX idx_employees_active ON employees (active);
